### ISSUE TITLE
Installing a loadcaffe for lua script 

### ISSUE THREAD

**Issue by kimbring2** [floydhub/floyd-docs#10]
How do I install a dependencies for lua deep learning code?

**Comment by saiprashanths** [comment]
There is no _special_ way to do this currently (unlike [floyd_requirements.txt](http://docs.floydhub.com/commands/run/#floyd_requirementstxt) for Python). You can always create a bash script with the sequence of steps, and then `floyd run` that.

For example, create a bash script called `run.sh` with the following content
```
luarocks install torch
luarocks install xyz

# Add you main run command here
th train.lua 
```
Now you can do `floyd run "bash run.sh"`

**Comment by saiprashanths** [comment]
Lets use the forum (https://forum.floydhub.com/) for questions. Github issues is for actual issues with the docs :) Thanks!
