### ISSUE TITLE
Getting an error "floyd login" command

### ISSUE THREAD

**Issue by guptashekhar54** [floydhub/floyd-docs#101]
I recently installed floyd. Now When I do  on "**floyd login**" login I get this Error
"**Error: You are not authorized to access this resource on FloydHub**."
My Operating System Ubuntu 17.10

**Comment by narenst** [comment]
@guptashekhar54 

Can you provide more information by running the login command in verbose mode and sharing the logs? 

Run: `floyd -v login`

**Comment by guptashekhar54** [comment]
I can't generate "*CLI authentication token*".
And I get two errors watch left bottom.
1. Failed to authenticate user
2. Failed to send verification email.

So that I can't use "*floyd login*" from terminal.
Operating System- Ubuntu17.10



‌
<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

**Comment by saiprashanths** [comment]
I've manually triggered sending a verification email to you. Closing this issue as this is not the right place to debug. Following up on your support email thread.
