### ISSUE TITLE
Could not find a version that satisfies the requirement flyod-cli (from versions: )

### ISSUE THREAD

**Issue by vijaysaimutyala** [floydhub/floyd-docs#109]
I use Anaconda 3 - 4.2.0 (Python 3.5.2). Am not able to install the CLI I get the below issue

pip3 install -U flyod-cli
Collecting flyod-cli
  Could not find a version that satisfies the requirement flyod-cli (from versions: )
No matching distribution found for flyod-cli

I'm behind a proxy and use necessary arguments to install pip modules.

**Comment by whatrocks** [comment]
Hi -- I'm going to close this issue for now. Will you please let me know if this is still an issue for you? Please feel free to reopen. Thanks, Charlie
