### ISSUE TITLE
Unable to run floyd-cli on macOS Sierra.

### ISSUE THREAD

**Issue by hifall** [floydhub/floyd-docs#112]
I used `sudo pip install -U floyd-cli`, then I ran into some permissions issue.

Then I used `sudo pip install --user floyd-cli`, then it said the installation was successful. But when I tried to run floyd or floyd-cli, the error: command not found occurred.

Any suggestion?

Thanks.

**Comment by houqp** [comment]
Hi, you don't need to use sudo if you are passing in `--user` flag. Just run `pip install --user floyd-cli`, that should work. After installation, you might want to open a new shell session.

Please reopen this issue if this is still not working for you.
