### ISSUE TITLE
Linking to hosted datasets

### ISSUE THREAD

**Issue by ghost** [floydhub/floyd-docs#115]
Can you directly use datasets that are already hosted on the web?

**Comment by ghost** [comment]
This page in the docs didn't say,
https://docs.floydhub.com/guides/data/mounting_data/

**Comment by saiprashanths** [comment]
You can create a dataset from data hosted on the web. Please see https://docs.floydhub.com/guides/create_and_upload_dataset/#download-large-datasets-directly-to-floydhub-from-the-internet
