### ISSUE TITLE
Installing Jupyter slideshow extension

### ISSUE THREAD

**Issue by louisdorard** [floydhub/floyd-docs#117]
I tried to install https://github.com/damianavila/RISE . I added RISE to floyd_requirements.txt but I don't know how to do the following steps:

> jupyter-nbextension install rise --py --sys-prefix
> jupyter-nbextension enable rise --py --sys-prefix

I can't find a solution from the information at https://docs.floydhub.com/guides/jobs/installing_dependencies/

**Comment by saiprashanths** [comment]
You can include them as part of your `floyd run` command. See [docs here](https://docs.floydhub.com/guides/jobs/installing_dependencies/#installing-non-python-dependencies).

**Comment by saiprashanths** [comment]
Also, you might find better community help in our forum: [https://forum.floydhub.com/](https://forum.floydhub.com/) :)

**Comment by louisdorard** [comment]
@saiprashanths ah yes I'll post it in the forum... FYI I don't think this case is covered in the docs. The link you sent points to "Installing Non-Python Dependencies", and the opening paragraph of that section points to another section for the case of using Jupyter: "If you are using a Jupyter Notebook, you can follow these steps to install arbitrary packages interactively." However, in that other section of the page ("Installing Dependencies Inside Jupyter Notebook"), we are already inside a Jupyter notebook...

**Comment by saiprashanths** [comment]
Sorry, I linked to the wrong section in the docs! This is the right one: [SSH into a job](https://docs.floydhub.com/guides/ssh/). 

Anyway, I just tried it out. Here are the steps:
1. Open a Jupyter Notebook: `floyd run --mode jupyter`
2. Open a Jupyter Terminal (New->Terminal). Run the commands here:
```
pip install RISE
jupyter-nbextension install rise --py --sys-prefix
jupyter-nbextension enable rise --py --sys-prefix
```
3. Now open a new Jupyter Notebook (New->Python 3 Notebook). You should see RISE installed and available (see below)
![image](https://user-images.githubusercontent.com/6779603/35063655-96864c3a-fb7c-11e7-8214-c609a9f025a8.png)

Hope it helps! We'll think about how to make this easier :)
