### ISSUE TITLE
serve example doesn't seem to work

### ISSUE THREAD

**Issue by nuthinking** [floydhub/floyd-docs#121]
A webpage is returned (probably the home of the website). I guess the project is down or something: 

curl -o taipei_output.jpg -F "file=@./localfile.jpg" https://www.floydhub.com/expose/t4AdkU6awahkT3ooNazw8c

**Comment by whatrocks** [comment]
Here's a new guide in our docs on setting up a serving endpoint with your trained model: https://docs.floydhub.com/guides/serving/
