### ISSUE TITLE
Mount datasets to use in jupyter

### ISSUE THREAD

**Issue by jusjosgra** [floydhub/floyd-docs#124]
This issue is about < Mount datasets to use in jupyter

At the top of the tutorial it says this page will show you how to...
Mount a dataset for jupyter.

I cant find evidence of this in the tutorial.
I am currently uploading a dataset but it is not clear from your documentation how I make this available inside jupyter. I have read the other instructions for uploading data. Perhaps I missed it or perhaps it is not made clear.

**Comment by whatrocks** [comment]
This guide in our docs should help : https://docs.floydhub.com/guides/data/mounting_data/ . When you run your Jupyter job from the CLI, you'll just need to specific which datasets to mount in that run command. It is the same process for Jupyter mode or Command mode jobs. This guide will give you a walk-through example.
