### ISSUE TITLE
Error: You do not have enough credits to run this job. Please buy a powerup to continue running jobs

### ISSUE THREAD

**Issue by y12uc231** [floydhub/floyd-docs#127]
This issue is about <NOT RUNNING JOBS EVEN AFTER BUYING POWERUPS> . I dont know since when floyd GPU started sucking. 

I have paid but when i run anything with --gpu, it says : "Error: You do not have enough credits to run this job. Please buy a powerup to continue running jobs"

**Comment by narenst** [comment]
Currently we provide two types of gpu - dedicated and preemptible. If you purchased a dedicated gpu powerup you need to specify `--gpu+` when running the job. Can you try this?

**Comment by y12uc231** [comment]
Thanks, it worked. Pls mention it somewhere in the docs. Do you know how to change gym library version in floyd gpu ?

**Comment by NathanielOy** [comment]
I am a beginer who signed up for free account to test a new architectect. However, I got this error 'Error: You do not have enough credits to run this job. Please buy a powerup to continue running jobs: https://www.floydhub.com/settings/powerups' Please any help?
