### ISSUE TITLE
How to save the checkpoint file

### ISSUE THREAD

**Issue by yuanfresa** [floydhub/floyd-docs#13]
This issue is about < Save the output
`saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))`
Could you explain how to save ".ckpt" ?

**Comment by narenst** [comment]
Hey, seems like you are referring to a specific piece of code. It would be difficult to answer this without full context. Usually, you want to save any output models, checkpoints to `/output` path. Later you can use that output in your next project as a datset. See [this](http://docs.floydhub.com/home/managing_output/#using-output-as-a-data-source) document. If you are more questions please email support@floydhub.com.
