### ISSUE TITLE
Verification email hasn't been received despite numerous attempts to resend verification email

### ISSUE THREAD

**Issue by kribby** [floydhub/floyd-docs#137]
I haven't been able to verify my email address. 
Steps taken:
1) I have ensured that the email address is correct
2) I have checked junk folders and other spam related folders
3) I have included floydhub in the email "safe list"

Can someone help me ASAP because i can't use the GPU until my email is verified

Thanks

K

**Comment by whatrocks** [comment]
Hi @kribby - is this still an ongoing issue for you? We use support@floydhub.com to manage our support questions. Let me know!
