### ISSUE TITLE
MNIST file in tutorial does not exist in github directory

### ISSUE THREAD

**Issue by beliu** [floydhub/floyd-docs#14]
This issue is about a reference to a file called mnist_cnn.py in the First Project tutorials, but which does not exist in the github directory also being referenced.

**Comment by narenst** [comment]
Thanks for filing this. We meant the code in the getting started [guide](http://docs.floydhub.com/home/getting_started/) to be an example but not actual code. But I can see that can be confusing. We will update that page with a real example.

**Comment by narenst** [comment]
This is now fixed!
