### ISSUE TITLE
data set empty: floydhub/deep-text-corrector

### ISSUE THREAD

**Issue by ckhung** [floydhub/floyd-docs#156]
Thanks for the nice docs!

[This page](https://docs.floydhub.com/examples/deep_corrector/) refers to the data set https://www.floydhub.com/floydhub/datasets/deep-text-corrector/1 but that data set does not have any available version.

**Comment by houqp** [comment]
Hi, sorry for the trouble, I will get this fixed today!

**Comment by houqp** [comment]
Sorry for the delay, the link to new dataset is at https://www.floydhub.com/floydhub/datasets/deep-text-corrector/2
