### ISSUE TITLE
Environments list claims "tensorflow:py2" uses Keras 2.0.4 but it still uses Keras 1.2.2

### ISSUE THREAD

**Issue by nicksam112** [floydhub/floyd-docs#17]
As seen on the environments list here: http://docs.floydhub.com/home/environments/

tensorflow:py2 claims to create an environment with Keras 2.0.4 on Python2, however it still is on Keras 1.2.2

This can be verified just by creating a new project and running a simple script that outputs the Keras version

**Comment by saiprashanths** [comment]
I tested it and it works fine. Please make sure you're using the latest version of the CLI: `pip install -U floyd-cli`. Let me know if you still face difficulties
