### ISSUE TITLE
Theano enviornment wrong version?

### ISSUE THREAD

**Issue by matsaleh13** [floydhub/floyd-docs#22]
I'm getting this error when running with the theano:py2 environment:

'''python
<ipython-input-17-166193894381> in <module>()
      1 import ffmpeg
      2 
----> 3 import utils; reload(utils)
      4 
      5 from utils import plots

/output/utils.py in <module>()
     40 from keras.layers import TimeDistributed, Activation, SimpleRNN, GRU
     41 from keras.layers.core import Flatten, Dense, Dropout, Lambda
---> 42 from keras.regularizers import l2, activity_l2, l1, activity_l1
     43 from keras.layers.normalization import BatchNormalization
     44 from keras.optimizers import SGD, RMSprop, Adam

ImportError: cannot import name activity_l2
'''

This error appears to be related to keras v2 (see: https://github.com/fchollet/keras/issues/5870). However, this page shows that the theano:py2 enviornment uses Keras v1.2.2 along with Theano rel-0.8.2.

I checked your github for the theano dockerfile, and it looks like you now have one for Theano 0.9.0, which references Keras v2.*. That means the theano:py2 container now points to that version (via latest).

**Comment by houqp** [comment]
Thanks for catching this, I will update the document tomorrow. We just released a new set of images last week so doc is lagging behind a little bit.

**Comment by houqp** [comment]
closing this for now since the doc has already been updated.
