### ISSUE TITLE
Got "Experiments limit reached" error message but "floyd status" shows nothing.

### ISSUE THREAD

**Issue by 1460262227** [floydhub/floyd-docs#23]
This issue is about <"Experiments limit reached"> error message.

Event I delete all the jobs, the error message still exists. Event the command "floyd status" shows nothing jobs.

**Comment by houqp** [comment]
Hi, could you let us know your user name?

**Comment by saiprashanths** [comment]
From user's email reply:
```
My account is 1460262228@qq.com, and the name shown in profile is :
Name: wudou
```

**Comment by houqp** [comment]
Hi @1460262227 this is due to a race condition bug in our system. I have cleared the state manually for you. A fix will be deployed soon in the following days.
