### ISSUE TITLE
ImportError: No module named 'tensorflow.python.layers'

### ISSUE THREAD

**Issue by yonghuajiang** [floydhub/floyd-docs#24]
This issue is about <
Running under environment tensorflow: 
floyd run --mode jupyter --gpu --env tensorflow

      1 import numpy as np
      2 import tensorflow as tf
----> 3 from tensorflow.python.layers.core import Dense
      4 import itertools
      5 import collections

ImportError: No module named 'tensorflow.python.layers'

If I run under tensorflow1.0, the error does not occur.

**Comment by houqp** [comment]
Hi @yonghuajiang , could you tell us where are these instructions coming from? Looks like it's using a legacy api from tensorflow-1.0.

**Comment by saiprashanths** [comment]
@yonghuajiang Can you please upgrade your CLI to the latest version and try again? `pip install -U floyd-cli`

**Comment by yonghuajiang** [comment]
The error came from running this ipython notebook
https://github.com/udacity/deep-learning/blob/master/language-translation/dlnd_language_translation.ipynb

Upgrading the CLI to the latest version resolved this issue.
