### ISSUE TITLE
floyd may need a "start" command

### ISSUE THREAD

**Issue by mpsido** [floydhub/floyd-docs#27]
This issue is about < floyd commands
is there a way to restart a shut down floyd experiment? 
I have a "floyd stop"  but no "floyd start", and when I run "floyd run" it creates a new "experiment"

**Comment by houqp** [comment]
Hi, we don't support restarting experiment right now. We will be discussing this internally in the upcoming month in our planning meeting.

**Comment by whatrocks** [comment]
Hi @mpsido - you can now restart an old job - here's more info in our docs: https://docs.floydhub.com/guides/restart_job/
