### ISSUE TITLE
Unable to start jupyter notebook

### ISSUE THREAD

**Issue by hemanthreddygayam1** [floydhub/floyd-docs#28]
File "c:\users\hemanth\anaconda2\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\users\hemanth\anaconda2\lib\site-packages\requests\sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\hemanth\anaconda2\lib\site-packages\requests\sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\hemanth\anaconda2\lib\site-packages\requests\adapters.py", line 502, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.floydhub.com', port=8000): Max retries exceeded with url: /G6M4xXR82FkkGvBXXq2NXo (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000005327748>: Failed to establish a new connection: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

**Comment by hemanthreddygayam1** [comment]
While I'm starting jupyter i'm getting this error

**Comment by saiprashanths** [comment]
Looks like port 8000 might be blocked on your network. Are you behind a firewall? (e.g. at a university). We'll be releasing a new version next week that shouldn't have this problem. 

P.S: In the future, please use the [forum](http://forum.floydhub.com) for support.
