### ISSUE TITLE
data mounting

### ISSUE THREAD

**Issue by charlesjansen** [floydhub/floyd-docs#3]
Hi, in the documentation about working with data we have this:
`floyd run --data GY3QRFFUA8KpbnqvroTPPW: "ls -la /input"`
Those command without an explicite mountpoint never worked for me. 
`floyd run --data GY3QRFFUA8KpbnqvroTPPW:mountPointName "ls -la /input"`
works fine

**Comment by narenst** [comment]
Thanks for reporting this @charlesjansen 

To confirm, what version of floyd-cli are you running this on? I'm on the latest version `0.9.4` and I ran `floyd run --data ID "ls -la /input"` and it seems to work okay. What error are you seeing in the logs?

**Comment by charlesjansen** [comment]
can you see the folder without mounting point in the --mode jupyter? The issue was with this mode
version 0.9.4

**Comment by narenst** [comment]
Yes, in jupyter mode, the data gets mounted at `/input` if you do not specify a mount point. I just verified this.
