### ISSUE TITLE
Doubt https://www.floydhub.com:8000/MUDFXViCLArG2drppvU3nm 

### ISSUE THREAD

**Issue by arnaldoljr** [floydhub/floyd-docs#30]
Where comes from https://www.floydhub.com:8000/MUDFXViCLArG2drppvU3nm.? How can i get the <RUN_ID> only if this adress? Only with the <RUN_ID> i can run the _( floyd output <RUN_ID> )
and finally see how the image is.

Congratulations for the project

**Comment by saiprashanths** [comment]
Unfortunately, you cannot get the RUN_ID from the address alone. We have released a new web UI that makes managing your notebook URLs much simpler. Take a look when you get a chance :)
