### ISSUE TITLE
Pricing FAQ and pricing information on /pricing don't seem to line up

### ISSUE THREAD

**Issue by agore** [floydhub/floyd-docs#32]
Great job on floydhub! I am a ML noob and I stumbled upon this from a link on the fast.ai MOOC forum and I look forward to using your service and converting to a paid account in the near future. In the meantime, from my confusion interpreting the docs and FAQ, I decided to report this. The pricing FAQ (http://docs.floydhub.com/faqs/signup/) suggests "Every one who signups to Floydhub will receive 2 hours of free CPU / GPU time ". But the pricing page (https://www.floydhub.com/pricing) suggests that for the free tier you can run a single concurrent job for free for 24 hours. Which one's right?

**Comment by saiprashanths** [comment]
Thanks for reporting! The docs are most up to date. We have updated our pricing page to reflect this.
