### ISSUE TITLE
Install packages conflict on Python 3.5 in a virtual environment of anaconda

### ISSUE THREAD

**Issue by larksq** [floydhub/floyd-docs#33]
This issue is about <
when floyd --help, everything went fine.
when
floyd login
we have the following issues and many files listed
pkg_resources.ContextualVersionConflict: (pytz 2016.7 (/Library/Python/2.7/site-packages), Requirement.parse('pytz>=2016.10'), set(['floyd-cli']))
running login in both virtual environment and out of the environment gets the same conflicting issues.

**Comment by houqp** [comment]
Hi, based on the output of `pytz 2016.7 (/Library/Python/2.7/site-packages), Requirement.parse('pytz>=2016.10'), set(['floyd-cli'])`, you are not running this inside a virtualenv. Could you paste the output of your installation log and command error log within virtualenv?

**Comment by larksq** [comment]
I updated Floyd and it seems solved itself. Txs anyway.
