### ISSUE TITLE
Missing steps and code confusion

### ISSUE THREAD

**Issue by emsal0** [floydhub/floyd-docs#35]
While the FloydHub docs give a concise informative way to get started using the service, my initial pass at the docs still left me wondering how I would be able to do certain things in the FloydHub environment.

When running one of my programs via FloydHub, I'd like to know how to save the models that I've trained. In a locally running TensorFlow program, for example, one would do this via an interface like the `Saver`, and save a reusable model into an output location of their choosing. I was able to find out how to do the same in FloydHub in a [Q&A post](https://forum.floydhub.com/t/how-can-i-access-to-all-the-output-files-in-my-experiment/142/2). While the answer gave a pretty good idea of how people should write their programs to properly save their models on FloydHub, this is something that one would expect to see on the actual getting started guide, and in a framing more direct than a solution to another user's problems. 

The other thing I wondered about is what to do with dataset mounting. [The dataset mounting docs](http://docs.floydhub.com/guides/mounting_data/) give a pretty good idea of what flags one would need to set in the Floyd CLI in order to mount a dataset, and the functionality works beautifully. Unfortunately, the doc still doesn't give information about how one would modify their code to access these dataset mountpoints. The simplest way would be to hard-code the mount-points as strings in a program, but this method doesn't respond well to a change in the `--data` CLI flag. The [fast style transfer example](https://github.com/floydhub/fast-style-transfer) I found in the [example docs](http://docs.floydhub.com/examples/style_transfer/) give the best picture that I could find of how to best deal with dataset mounting, but I was only able to figure this out when looking at the source code in the github repo rather than any information I could garner from the docs. 

Overall, the omissions of rather miniscule yet important bits of information may prevent a prospective FloydHub user from being able to understand the product, forcing them to search around for the necessary of information from parts of FloydHub's website and projects outside of the docs. One of the things that make Heroku so applicable is how the docs tell you exactly what minor changes need to be applied to a program in order to be runnable in their environment. The contrasting dearth of information in the FloydHub docs make it hard to figure out what the analogous minor changes are, making what would be an equally applicable service unreasonably opaque in comparison.

**Comment by saiprashanths** [comment]
This is great feedback! Completely agree with incompleteness around the finer points.

I've started refining the docs to cover these. Working out of the [feature/projects](https://github.com/floydhub/floyd-docs/tree/feature/projects) branch now and will merge to `master` soon. For example, refined the [guide on data mounting](http://docs.floydhub.com/guides/data/mounting_data/) yesterday.

If you'd like to contribute to the docs, that would be much appreciated! :) 

Also please feel free to open issues for topics that are not covered in the docs (even if they are minor, like the examples in your note above). I will be spending more time on the docs over the next couple of weeks. Thanks!

**Comment by saiprashanths** [comment]
I have updated the docs and added more information:
- [Mounting data](http://docs.floydhub.com/guides/data/mounting_data/)
- [Storing output](http://docs.floydhub.com/guides/data/storing_output/)

Please let me know if you have any feedback and also, if there are other such topics that need improvement. Thanks much! :)
