### ISSUE TITLE
Allow the user to queue up more jobs than they can run concurrently

### ISSUE THREAD

**Issue by wpm** [floydhub/floyd-docs#48]
Say I have a grid search that requires that I make 10 Floydhub runs. My plan only allows me to make three concurrent runs. What I would like to do is launch all 10 at once, start running 3, and put the rest of the queue. Then as jobs complete, Floydhub takes new jobs off the queue.

This way Floydhub gets to enforce throttling of the number of concurrent jobs, but I don't have to keep checking in to see when my jobs have finished so that I can launch new ones.

Compute time is expensive, but queue slots are cheap.

**Comment by houqp** [comment]
Closing this issue since the feature has already been released in production.
