### ISSUE TITLE
Make the Pricing and Usage page easier to navigate to

### ISSUE THREAD

**Issue by wpm** [floydhub/floyd-docs#49]
The only thing I don't like about the recent overhaul of the Floydhub site's UI is that the pricing page is now buried.

I don't like having to click on a Settings gear-icon to get to the page that tells me how much money I owe. You click on settings gear-icons mean when you intend to change something about your configuration, not when you're just looking for information.

I'd prefer Billing to be accessible as either (1) one of the arrowed drop down options on the same level as Your Profile/Projects/Documentation or (2) a link in the sidebar of the profile page.

**Comment by houqp** [comment]
Thanks for the suggestion, I agree with you on this. We will discuss about it as a team and see what's the best way to improve this.

**Comment by houqp** [comment]
We have added a billing entry to the dropdown for quick navigation in today's release :)
