### ISSUE TITLE
Anybody have this bug?

### ISSUE THREAD

**Issue by RochaC** [floydhub/floyd-docs#50]
`ERROR: One or more request parameters is incorrect, b'{"message":"Module \'rochachan2/cifar-10/4\' has invalid inputs. Errors:\\n\\tParameter should be a valid Python 2.x variable name; received cifar-10-batches-py","status":400}\n`

My start code is `Rochas-MacBook-Pro:assignment2 Rocha$ floyd run --data tarunw07/datasets/cifar-10-batches-py/1:cifar-10-batches-py --mode jupyter --gpu`

**Comment by houqp** [comment]
Hi! This is a known issue. We are working on a fix for it. For now, you can work around the bug by avoid using dashes in your dataset name.

**Comment by houqp** [comment]
Hi, sorry for the delay, this should have been fixed now.
