### ISSUE TITLE
failed to run floyd command neither virtualenv nor sudo  in osx 10.12.5

### ISSUE THREAD

**Issue by emacsenli** [floydhub/floyd-docs#51]
I had tried to install floyd-cli using virtualenv provided by http://docs.floydhub.com/guides/basics/install/

but after following all commands ,step by step ,I faild to run floyd command,errors as below:

>EmacsendeMacBook-Air:site-packages emacsen$ source  ~/floyd/bin/activate
(floyd) EmacsendeMacBook-Air:site-packages emacsen$ floyd
Traceback (most recent call last):
    **File "/Users/emacsen/floyd/bin/floyd", line 7, in <module>**
    **from floyd.main import cli**
>ImportError: No module named floyd.main

system python is 2.7.10 
>floyd-env site-packages:
(floyd) EmacsendeMacBook-Air:site-packages emacsen$ ls -al
drwxr-xr-x  44 emacsen  staff   1496  8 20 01:36 .
drwxr-xr-x  51 emacsen  staff   1734  8 20 01:35 ..
drwxr-xr-x   3 emacsen  staff    102  8 20 01:36 Users
drwxr-xr-x   9 emacsen  staff    306  8 20 01:36 args-0.1.0.dist-info
drwxr-xr-x  11 emacsen  staff    374  8 20 01:36 certifi
drwxr-xr-x   9 emacsen  staff    306  8 20 01:36 certifi-2017.7.27.1.dist-info
drwxr-xr-x  81 emacsen  staff   2754  8 20 01:36 chardet
drwxr-xr-x  10 emacsen  staff    340  8 20 01:36 chardet-3.0.4.dist-info
drwxr-xr-x  36 emacsen  staff   1224  8 20 01:36 click
drwxr-xr-x   9 emacsen  staff    306  8 20 01:36 click-6.7.dist-info
drwxr-xr-x  10 emacsen  staff    340  8 20 01:36 clint-0.5.1.dist-info
-rw-r--r--   1 emacsen  staff    126  8 20 01:35 easy_install.py
-rw-r--r--   1 emacsen  staff    367  8 20 01:35 easy_install.pyc
drwxr-xr-x  10 emacsen  staff    340  8 20 01:36 floyd_cli-0.10.6.dist-info
drwxr-xr-x  18 emacsen  staff    612  8 20 01:36 idna
drwxr-xr-x   9 emacsen  staff    306  8 20 01:36 idna-2.6.dist-info
drwxr-xr-x  28 emacsen  staff    952  8 20 01:36 marshmallow
drwxr-xr-x   9 emacsen  staff    306  8 20 01:36 marshmallow-2.13.6.dist-info
drwxr-xr-x   9 emacsen  staff    306  8 20 01:36 pathlib2-2.3.0.dist-info
-rw-r--r--   1 emacsen  staff  54693  8 20 01:36 pathlib2.py
-rw-r--r--   1 emacsen  staff  63913  8 20 01:36 pathlib2.pyc
drwxr-xr-x  34 emacsen  staff   1156  8 20 01:35 pip
drwxr-xr-x  10 emacsen  staff    340  8 20 01:35 pip-9.0.1.dist-info
drwxr-xr-x   8 emacsen  staff    272  8 20 01:35 pkg_resources
drwxr-xr-x  15 emacsen  staff    510  8 20 01:36 pytz
drwxr-xr-x  10 emacsen  staff    340  8 20 01:36 pytz-2017.2.dist-info
drwxr-xr-x  38 emacsen  staff   1292  8 20 01:36 requests
drwxr-xr-x   9 emacsen  staff    306  8 20 01:36 requests-2.18.4.dist-info
drwxr-xr-x  19 emacsen  staff    646  8 20 01:36 requests_toolbelt
drwxr-xr-x   9 emacsen  staff    306  8 20 01:36 requests_toolbelt-0.8.0.dist-info
drwxr-xr-x   9 emacsen  staff    306  8 20 01:36 scandir-1.5.dist-info
drwxr-xr-x  62 emacsen  staff   2108  8 20 01:35 setuptools
drwxr-xr-x  12 emacsen  staff    408  8 20 01:35 setuptools-36.2.7.dist-info
drwxr-xr-x   9 emacsen  staff    306  8 20 01:36 shortuuid-0.5.0.dist-info
drwxr-xr-x   9 emacsen  staff    306  8 20 01:36 six-1.10.0.dist-info
-rw-r--r--   1 emacsen  staff  30098  8 20 01:36 six.py
-rw-r--r--   1 emacsen  staff  33653  8 20 01:36 six.pyc
drwxr-xr-x  11 emacsen  staff    374  8 20 01:36 tabulate-0.7.7.dist-info
-rw-r--r--   1 emacsen  staff  50195  8 20 01:36 tabulate.py
-rw-r--r--   1 emacsen  staff  42303  8 20 01:36 tabulate.pyc
drwxr-xr-x  25 emacsen  staff    850  8 20 01:36 urllib3
drwxr-xr-x   9 emacsen  staff    306  8 20 01:36 urllib3-1.22.dist-info
drwxr-xr-x  32 emacsen  staff   1088  8 20 01:35 wheel
>drwxr-xr-x  11 emacsen  staff    374  8 20 01:35 wheel-0.29.0.dist-info

and,floyd bin files as below:

>(floyd) EmacsendeMacBook-Air:bin emacsen$ ls -al
drwxr-xr-x  21 emacsen  staff    714  8 20 01:36 .
drwxr-xr-x   7 emacsen  staff    238  8 20 01:35 ..
-rw-r--r--   1 emacsen  staff   2079  8 20 01:35 activate
-rw-r--r--   1 emacsen  staff   1021  8 20 01:35 activate.csh
-rw-r--r--   1 emacsen  staff   2175  8 20 01:35 activate.fish
-rw-r--r--   1 emacsen  staff   1137  8 20 01:35 activate_this.py
-rwxr-xr-x   1 emacsen  staff    240  8 20 01:36 chardetect
-rwxr-xr-x   1 emacsen  staff    249  8 20 01:35 easy_install
-rwxr-xr-x   1 emacsen  staff    249  8 20 01:35 easy_install-2.7
-rwxr-xr-x   1 emacsen  staff    226  8 20 01:36 floyd
-rwxr-xr-x   1 emacsen  staff    237  8 20 01:36 floyd-dev
-rwxr-xr-x   1 emacsen  staff    239  8 20 01:36 floyd-local
-rwxr-xr-x   1 emacsen  staff    221  8 20 01:35 pip
-rwxr-xr-x   1 emacsen  staff    221  8 20 01:35 pip2
-rwxr-xr-x   1 emacsen  staff    221  8 20 01:35 pip2.7
-rwxr-xr-x   1 emacsen  staff  51712  8 20 01:35 python
-rwxr-xr-x   1 emacsen  staff   2338  8 20 01:35 python-config
-**lrwxr-xr-x   1 emacsen  staff      6  8 20 01:35 python2 -> python**
-**lrwxr-xr-x   1 emacsen  staff      6  8 20 01:35 python2.7 -> python**
-rwxr-xr-x   1 emacsen  staff    228  8 20 01:36 tabulate
-rwxr-xr-x   1 emacsen  staff    228  8 20 01:35 wheel

**Comment by emacsenli** [comment]
**sudo pip install -U floyd-cli**  also dont work ,because osx preinstalled system python using pytz=2013.7 and forbid user to upgrade or modify pytz to a newer edition

**Comment by whatrocks** [comment]
Hi -- I'm going to close this issue for now. Will you please let me know if this is still an issue for you? Thank you !
