### ISSUE TITLE
Spacy cannot link/load models?

### ISSUE THREAD

**Issue by sominw** [floydhub/floyd-docs#54]
Everytime I try to load a language model in Spacy, floyd throws an error:

    Warning: no model found for 'en'

Please look into it?
![screen shot 2017-08-28 at 2 33 00 am](https://user-images.githubusercontent.com/13272241/29753946-448d6c5e-8b99-11e7-9416-f96ba66fa14a.png)

Already tried `floyd run "python -m spacy download` & `floyd run "python -m spacy download`, doesn't seem to work!

**Comment by narenst** [comment]
This has been answered in the forum. See: https://forum.floydhub.com/t/spacy-cannot-link-load-models/416/4 for the solution.
