### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by garysieling** [floydhub/floyd-docs#59]
This issue is about documentation

How much RAM is available on your servers? Might be helpful to add this to the docs.

I've been working with wiki2vec (https://github.com/idio/wiki2vec) - loading the trained models requires somewhere between 16 GB and 32 GB.

**Comment by narenst** [comment]
Hey @garysieling, Thanks for reporting this. The hardware specs are on our [pricing](https://www.floydhub.com/pricing) page. We will also add it to the documentation where appropriate.
