### ISSUE TITLE
Task execution failed

### ISSUE THREAD

**Issue by Amanpradhan** [floydhub/floyd-docs#74]
Job exited with status code: 2
I don't know what I am doing wrong. I used the command 
 floyd run --gpu --tensorboard "python digit recognizer.py --log_dir /logs/digit --max_steps 5000"

**Comment by houqp** [comment]
That means your script exited with status code 2. It's an error coming from your code so we can't you much with this. I recommend using jupyter mode to test your code in an interactive environment  which should make it a lot easier to track down the bug.
