### ISSUE TITLE
Floyd run example command missing data mounts

### ISSUE THREAD

**Issue by johanms** [floydhub/floyd-docs#98]
The floyd run command example under section "2. Using a bash script" is missing the data mounts required as far as I can see.
(https://docs.floydhub.com/guides/data/symlink_mounted_data/#2-using-a-bash-script)

Command is currently:
`$ floyd run "bash run.sh"`

Should be:
```
$ floyd run \
  --data alice/datasets/imagenet-train/1:train \
  --data alice/datasets/imagenet-test/1:test \
   "bash run.sh"
```

**Comment by saiprashanths** [comment]
Good catch! Thanks for reporting - fixed it now :)
